# PATH TO BE CHANGED 

samples:
  patient01: /data/lrs_bams/patient01.sort.bam #sample ID
  patient02: /data/lrs_bams/patient02.sort.bam

path: "/data/lrs_results/"
ref: "/DATA/Reference/hg38.fa"
threads: 16

bed: "PANEL_OA/optic_neuropathy_panel.bed"                  # panel regions for Clair3/cuteSV/straglr targeting
candidate_genes_list: "PANEL_OA/optic_neuropathy_genes.txt" # plain gene-symbol list (one per line) for AnnotSV
cpg: "chr1:1-100000"                                            # region(s) for modkit CpG extraction - adjust as needed

condaenv: "envs/"
modkitenv: "/tools/modkit/modkit"     
clair3env: "/tools/clair3/models/ont" # Clair3 ONT model directory (confirm it matches your basecaller model) 

# required by sniffles2_sv (--tandem-repeats)
vntr_bed: "/reference/human_GRCh38_no_alt_analysis_set.trf.bed"   # point this at your actual reference-wide VNTR bed

# required by vep_sv_annotation
vep_cache_dir: "/refs/vep_cache/"      # point this at your local VEP offline cache
vep_assembly: "GRCh38"                 # optional - already the default if omitted


# needLR population-AF backend - required for real AF output, not just annotation columns
needlr_backend_files: "/refs/needlr/backend/"   # path of  needLR cohort backend (e.g. the 1KGP-LRSC ONT bundle), must be included, opnly use when using customized control cohort

# TLDR 
tldr_elements: "/reference/teref.ont.human.fa"  # ALU/LINE1/SVA reference for TLDR
