# ============================================================
# LRS PIPELINE CONFIGURATION
# ============================================================

samples:
  patient01: "/DATA/casadei7/nanopore/DM1/14655native/bam/sup_met_hg38/14655native.bam" #/data/lrs_bams/patient01.sort.bam
  patient02: "/DATA/casadei7/nanopore/DM1/22_9814native/bam/sup_met_hg38/22_9814native.bam" #/data/lrs_bams/patient02.sort.bam

path: "/home/casadei7/SV-PIPELINE-main/outs"
ref: "/DATA/Reference/hg38.fa"
threads: 32

# ============================================================
# TARGET PANEL AND ANNOTATION FILES
# ============================================================
# Used by Clair3, cuteSV and targeted Straglr analysis

bed: "/home/casadei7/SV-PIPELINE-main/PANEL_OA/optic_neuropathy_panel.bed"
bedcutesv: "/home/casadei7/SV-PIPELINE-main/PANEL_OA/optic_neuropathy_panel_cutesv.bed"

# Gencode gene BED file for gene annotation
gene_bed: "/home/casadei7/SV-PIPELINE-main/reference/gencode.genes.hg38.sorted.bed"

# Plain-text candidate gene list, one gene symbol per line
candidate_genes_list: "/home/casadei7/SV-PIPELINE-main/PANEL_OA/optic_neuropathy_genes.txt"

delly_genome: "ont"

straglr_bed: null # genome-wide tandem-repeat expansion discovery
straglr_script: "/home/casadei7/straglr/straglr.py"

# null = extract CpG methylation genome-wide
# Set a region such as "chr3:193600000-193700000" if needed
cpg_region: null

# ============================================================
# ENVIRONMENTS
# ============================================================
condaenv: "/home/casadei7/SV-PIPELINE-main/envs/"
# Modkit executable
modkitenv: "/home/casadei7/dist_modkit_v0.6.4_cd85862/modkit"

# Clair3 ONT model directory.
# Confirm that this model matches the Dorado basecaller model.
clair3env: "/DATA/casadei7/BrainAging/Clair3_Models/r1041_e82_400bps_sup_v520/"

# ============================================================
# SNIFFLES2
# ============================================================

# Reference-wide VNTR BED file required by Sniffles2
vntr_bed: "/home/casadei7/SV-PIPELINE-main/reference/human_GRCh38_no_alt_analysis_set.trf.bed"
# false = standard SV calling
# true  = mosaic SV calling
sniffles_mosaic: false

# ============================================================
# VEP
# ============================================================

# Local offline VEP cache
# do this vep_install -a cf -s homo_sapiens -y GRCh38 -c /refs/vep_cache --CONVERT

reference_dir: "/DATA/Reference" # "/home/casadei7/SV-PIPELINE-main/reference"
vep_cache_dir: "/DATA/Reference/vep" # "/home/casadei7/SV-PIPELINE-main/reference/vep" 
vep_assembly: "GRCh38"

# ============================================================
# needLR
# ============================================================

# needLR population-AF backend.
# Must contain the required 1KGP-LRSC ONT backend files.
needlr_backend_files: null #"/home/casadei7/SV-PIPELINE-main/reference/needlr/backend/" # da scaricare e caricare sul folder 



# ============================================================
# TLDR
# ============================================================

# Must contain the ALU/LINE1/SVA reference sequences required by TLDR.
tldr_elements: "/home/casadei7/SV-PIPELINE-main/reference/teref.ont.human.fa"

# ============================================================
# phenotype correlation
# ============================================================

monarch_base_url: "https://api-v3.monarchinitiative.org/v3/api"
discovery_hpo_file: "/home/casadei7/SV-PIPELINE-main/reference/optic_neuropathy_hpo_terms.tsv"

# ============================================================
# ANNOTSV
#=============================================================
annotsv_annotations_dir: "/home/casadei7/SV-PIPELINE-main/reference/AnnotSV_annotations"
# Benign population AF threshold
annotsv_benign_af: 0.01
