#!/usr/bin/env python3
"""Show the SV size/type spectrum contributing to prioritized genes."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from plot_utils import first_existing, numeric, read_tsv, save_figure, set_thesis_style, style_axis


SIZE_GROUPS = [
    ("LT100KB", "<100 kb"),
    ("100KB_1MB", "100 kb–1 Mb"),
    ("1MB_10MB", "1–10 Mb"),
    ("GE10MB", "≥10 Mb"),
    ("BREAKEND", "Breakend"),
    ("UNKNOWN", "Unknown size"),
]


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input", required=True)
    p.add_argument("--out-prefix", required=True)
    p.add_argument("--top-n", type=int, default=25)
    return p.parse_args()


def group_size(value):
    text = str(value).strip().upper()

    if text.startswith("BREAKEND"):
        return "BREAKEND"

    # Final SV-gene candidate table generated by build_candidate_tables.py.
    if text in {"LT_100KB", "LT100KB"}:
        return "LT100KB"
    if text == "100KB_TO_1MB":
        return "100KB_1MB"
    if text == "1MB_TO_10MB":
        return "1MB_10MB"
    if text in {"GE_10MB", "GE10MB"}:
        return "GE10MB"

    # Backward compatibility with the detailed event table generated by
    # rank_sv_gene_events.py.
    if text in {"LT50_BP", "50BP_1KB", "1KB_10KB", "10KB_100KB"}:
        return "LT100KB"
    if text == "100KB_1MB":
        return "100KB_1MB"
    if text == "1MB_10MB":
        return "1MB_10MB"

    return "UNKNOWN"


def main():
    args = parse_args()
    set_thesis_style()
    df = read_tsv(args.input)

    id_col = first_existing(df, ["SV_ID", "ID"])
    gene_col = first_existing(df, ["GENES", "ANNotsv_Gene", "Gene", "GENE"])
    score_col = first_existing(
        df,
        [
            "FINAL_GENE_RELEVANCE_DISPLAY_SCORE",
            "GENE_RELEVANCE_DISPLAY_SCORE",
            "EVENT_GENE_RELEVANCE_SCORE",
            "INTEGRATED_DISCOVERY_SCORE",
        ],
    )
    panel_col = first_existing(df, ["PANEL_STATUS"])
    rank_col = first_existing(
        df,
        [
            "FINAL_EVENT_RANK_WITHIN_PANEL_STATUS",
            "EVENT_RANK_WITHIN_PANEL_STATUS",
        ],
    )
    if id_col is None or gene_col is None:
        raise ValueError("Event table needs SV_ID and gene columns.")
    # Final candidate tables use a coarser size grouping than the earlier
    # event ranking. Both describe the same four size ranges used here.
    size_col = first_existing(df, ["SV_SIZE_GROUP", "SV_EVENT_SIZE_CLASS"])
    type_col = first_existing(df, ["SVTYPE"])
    if size_col is None:
        raise ValueError("Event table needs SV_SIZE_GROUP or SV_EVENT_SIZE_CLASS.")

    work = df.copy()
    work["_gene"] = work[gene_col].fillna(".").astype(str)
    work = work[~work["_gene"].isin(["", ".", "NA", "N/A", "nan", "None"])].copy()
    work["_score"] = numeric(work[score_col]).fillna(0) if score_col else 0
    work["_size_group"] = work[size_col].map(group_size)
    if type_col:
        svtypes = work[type_col].fillna(".").astype(str).str.strip().str.upper()
        work["_breakpoint"] = svtypes.isin(["INV", "BND", "TRA"])
        # Breakends have no ordinary interval size, even if a span is reported.
        work.loc[svtypes.isin(["BND", "TRA"]), "_size_group"] = "BREAKEND"
    else:
        breakpoint_flag = work.get(
            "BREAKPOINT_DEFINED_EVENT", pd.Series("NO", index=work.index)
        )
        work["_breakpoint"] = (
            breakpoint_flag.fillna("NO").astype(str).str.upper().eq("YES")
        )

    work["_panel_group"] = (
        work[panel_col]
        .fillna("NONPANEL_GENE")
        .astype(str)
        .str.upper()
        .replace({"NON_PANEL": "NONPANEL_GENE"})
        if panel_col
        else "NONPANEL_GENE"
    )
    work["_rank"] = (
        numeric(work[rank_col])
        if rank_col
        else pd.Series(np.nan, index=work.index)
    )

    unique = (
        work.sort_values(
            ["_panel_group", "_rank", "_score", id_col, "_gene"],
            ascending=[True, True, False, True, True],
            na_position="last",
        )
        .drop_duplicates([id_col, gene_col], keep="first")
        .copy()
    )

    gene_priority = []
    for group in ["PANEL_GENE", "NONPANEL_GENE"]:
        sub = unique[unique["_panel_group"].eq(group)].copy()
        gene_rank = (
            sub.groupby("_gene")
            .agg(
                best_rank=("_rank", "min"),
                best_score=("_score", "max"),
            )
            .reset_index()
            .sort_values(
                ["best_rank", "best_score", "_gene"],
                ascending=[True, False, True],
                na_position="last",
            )
        )
        gene_priority.extend(
            gene_rank["_gene"].head(args.top_n).tolist()
        )
    unique = unique[unique["_gene"].isin(gene_priority)].copy()

    rows = []
    for gene in gene_priority:
        sub = unique[unique["_gene"].eq(gene)]
        row = {
            "gene": gene,
            "panel_status": str(sub["_panel_group"].iloc[0]),
            "gene_relevance_score": float(sub["_score"].max()),
            "unique_SVs": int(sub[id_col].nunique()),
            "breakpoint_defined_INV_BND": int(sub.loc[sub["_breakpoint"], id_col].nunique()),
        }
        for key, _label in SIZE_GROUPS:
            row[key] = int(sub.loc[sub["_size_group"].eq(key), id_col].nunique())
        rows.append(row)

    summary = pd.DataFrame(rows, columns=[
        "gene", "panel_status", "gene_relevance_score", "unique_SVs",
        "breakpoint_defined_INV_BND", *[key for key, _ in SIZE_GROUPS],
    ])

    prefix = Path(args.out_prefix)
    prefix.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(
        prefix.with_name(prefix.name + "_summary.tsv"),
        sep="\t",
        index=False,
    )

    plot = summary.iloc[::-1].reset_index(drop=True)
    y = np.arange(len(plot))

    fig, axes = plt.subplots(
        1,
        2,
        figsize=(15.5, max(7.5, 0.39 * len(plot) + 2.8)),
        gridspec_kw={"width_ratios": [1.45, 0.75]},
    )
    ax1, ax2 = axes

    left = np.zeros(len(plot))
    for key, label in SIZE_GROUPS:
        values = plot[key].to_numpy(dtype=float)
        color_options = {"color": "#999999"} if key == "UNKNOWN" else {}
        ax1.barh(y, values, left=left, label=label, **color_options)
        left += values

    ax1.set_yticks(y)
    ax1.set_yticklabels(plot["gene"])
    ax1.set_xlabel("Unique SVs overlapping gene")
    ax1.set_ylabel("Prioritized gene")
    ax1.set_title("SV size spectrum per prioritized gene")
    if plot.empty:
        ax1.text(0.5, 0.5, "No prioritized genes with SV events", ha="center",
                 va="center", transform=ax1.transAxes)
    ax1.legend(frameon=False, fontsize=8, ncol=2)
    style_axis(ax1, "x")

    bars = ax2.barh(y, plot["breakpoint_defined_INV_BND"])
    ax2.set_yticks(y)
    ax2.set_yticklabels([])
    ax2.set_xlabel("Unique INV/BND/TRA events")
    ax2.set_title("Breakpoint-defined events")
    style_axis(ax2, "x")
    for bar, count in zip(bars, plot["breakpoint_defined_INV_BND"]):
        if count:
            ax2.text(
                bar.get_width(),
                bar.get_y() + bar.get_height() / 2,
                f"  {int(count)}",
                va="center",
                fontsize=8,
            )

    fig.suptitle(
        "Structural-variant spectrum of prioritized genes",
        fontsize=16,
        fontweight="bold",
        y=0.995,
    )
    fig.text(
        0.5,
        0.012,
        "Counts represent unique SVs. Size/type composition is descriptive and does not increase pathogenicity priority.\n"
        "INV/BND/TRA counts indicate event types requiring breakpoint review; they do not establish gene disruption.",
        ha="center",
        fontsize=8.8,
    )
    fig.tight_layout(rect=[0, 0.05, 1, 0.965])
    outputs = save_figure(fig, prefix)
    plt.close(fig)

    print("[OK]", *outputs, sep="\n")


if __name__ == "__main__":
    main()
