#change PATH

ssamples:
  patient01: /data/srs_bams/patient01.sorted.bam
  patient02: /data/srs_bams/patient02.sorted.bam

path: "/data/srs_results/"
ref: "/refs/hg38/hg38.fa"
threads: 16

bed: "/PANEL_OA/optic_neuropathy_panel.bed"
candidate_genes_list: "/PANEL_OA/optic_neuropathy_genes.txt"

exclude_bed: "/reference/delly_hg38_exclude.bed"

expansionhunter_catalog: "/reference/variant_catalog_hg38_repeats.json"

# --- MELT: Mobile Element Insertions ---
melt_dir: "/Volumes/Samsung_T5/Reference/MELT/MELTv2.2.2"

melt_transposons: "/Volumes/Samsung_T5/Reference/MELT/MELTv2.2.2/me_refs/Hg38/mei_list.txt"

melt_genes_bed: "/Volumes/Samsung_T5/Reference/MELT/MELTv2.2.2/add_bed_files/Hg38/Hg38.genes.bed"

vep_cache_dir: "/refs/vep_cache"
vep_assembly: "GRCh38"

# Optional
# annotsv_annotations_dir: "/data/srs_results/reference/AnnotSV_annotations"
# hpo_terms: "HP:0000505,HP:0007675"
# deepvariant_version: "1.6.1"
# deepvariant_use_conda: false

condaenv: "envs/"
