#change PATH

ssamples:
  patient01: /data/srs_bams/patient01.sorted.bam
  patient02: /data/srs_bams/patient02.sorted.bam

path: "/data/srs_results/"
ref: "/refs/hg38/hg38.fa"
threads: 16

bed: "/panels/optic_neuropathy_mito_panel.bed"
candidate_genes_list: "/panels/optic_neuropathy_mito_panel_genes.txt"

exclude_bed: "/refs/hg38/delly_smoove_exclude.bed"

expansionhunter_catalog: "/refs/hg38/eh_variant_catalog_panel.json"

melt_dir: "/tools/MELTv2.2.2"
melt_transposons:
  - "/tools/MELTv2.2.2/me_refs/Hg38/ALU_MELT.zip"
  - "/tools/MELTv2.2.2/me_refs/Hg38/LINE1_MELT.zip"
  - "/tools/MELTv2.2.2/me_refs/Hg38/SVA_MELT.zip"
  - "/tools/MELTv2.2.2/me_refs/Hg38/HERVK_MELT.zip"

vep_cache_dir: "/refs/vep_cache"
vep_assembly: "GRCh38"

# Optional
# annotsv_annotations_dir: "/data/srs_results/reference/AnnotSV_annotations"
# hpo_terms: "HP:0000505,HP:0007675"
# deepvariant_version: "1.6.1"
# deepvariant_use_conda: false

condaenv: "envs/"
