configfile: "config_srs.yaml"

SAMPLES    = list(config["samples"].keys())
BAMS       = config["samples"]
PATH       = config["path"]
REF        = config["ref"]
THREADS    = config["threads"]
BED        = config["bed"]                     # panel/target regions (used for DeepVariant --regions restriction)
GENE_LIST  = config["candidate_genes_list"]     # plain gene-symbol list, same role as the LRS panel gene list
EXCLUDE    = config["exclude_bed"]              # Delly exclude regions (centromeres, telomeres, segdups)
EH_CATALOG = config["expansionhunter_catalog"]
MELT_DIR   = config["melt_dir"]                 # MELTv2 install dir (contains mei_list, add_bed_files, genes bed)
MELT_TRANSPOSONS = config["melt_transposons"]   # list of *_MELT.zip element refs (ALU, LINE1, SVA, HERVK...)
CONDAENV   = config["condaenv"]

# --- VEP (transcript-level consequence detail, parity with the LRS pipeline) ---
VEP_CACHE_DIR = config["vep_cache_dir"]
VEP_ASSEMBLY  = config.get("vep_assembly", "GRCh38")

# --- AnnotSV (optional HPO-term phenotype matching) ---
HPO_TERMS = config.get("hpo_terms", None)

rule all:
    input:
        expand(PATH + "{sample}/coverage/{sample}.mosdepth.global.dist.txt", sample=SAMPLES),
        expand(PATH + "{sample}/sv/manta/{sample}_manta.vcf.gz", sample=SAMPLES),
        expand(PATH + "{sample}/sv/delly/{sample}_delly.vcf.gz", sample=SAMPLES),
        expand(PATH + "{sample}/sv/merged/{sample}_merged_SV.vcf", sample=SAMPLES),
        expand(PATH + "{sample}/sv/merged/{sample}_merged_SV.annotsv.tsv", sample=SAMPLES),
        expand(PATH + "{sample}/sv/vep/{sample}_SV_VEP.txt", sample=SAMPLES),
        expand(PATH + "{sample}/mei/melt/{sample}.MEI.merged.vcf", sample=SAMPLES),
        expand(PATH + "{sample}/str/expansionhunter/{sample}_EH.vcf", sample=SAMPLES),
        expand(PATH + "{sample}/snp_deepvariant/{sample}.vcf.gz", sample=SAMPLES),
        expand(PATH + "{sample}/phasing/{sample}.phased.vcf.gz", sample=SAMPLES),
        expand(PATH + "{sample}/phasing/{sample}.phased.bam", sample=SAMPLES)

#######
# QC  #
#######

rule mosdepth_coverage:
    input:
        bam = lambda wc: BAMS[wc.sample]
    output:
        PATH + "{sample}/coverage/{sample}.mosdepth.global.dist.txt"
    conda:
        CONDAENV + "mosdepth.yaml"
    shell:
        """
        mosdepth -t {THREADS} {PATH}/{wildcards.sample}/coverage/{wildcards.sample} {input.bam}
        """

#####################################
# SV CALLING - Manta + Delly        #
#####################################

rule manta_sv:
    input:
        bam = lambda wc: BAMS[wc.sample],
        ref = REF
    output:
        vcf = PATH + "{sample}/sv/manta/{sample}_manta.vcf.gz"
    params:
        rundir = PATH + "{sample}/sv/manta/rundir"
    conda:
        CONDAENV + "manta.yaml"
    shell:
        """
        configManta.py --bam {input.bam} --referenceFasta {input.ref} --runDir {params.rundir}
        {params.rundir}/runWorkflow.py -m local -j {THREADS}
        cp {params.rundir}/results/variants/diploidSV.vcf.gz {output.vcf}
        tabix -p vcf {output.vcf}
        """

rule delly_sv:
    input:
        bam = lambda wc: BAMS[wc.sample],
        ref = REF,
        excl = EXCLUDE
    output:
        vcf = PATH + "{sample}/sv/delly/{sample}_delly.vcf.gz"
    params:
        bcf = PATH + "{sample}/sv/delly/{sample}_delly.bcf"
    conda:
        CONDAENV + "delly.yaml"
    shell:
        """
        delly call -x {input.excl} -g {input.ref} -o {params.bcf} {input.bam}
        bcftools view {params.bcf} -O z -o {output.vcf}
        tabix -p vcf {output.vcf}
        """

#############################
# WITHIN-PLATFORM SV MERGE  #
#############################

rule survivor_merge:
    input:
        manta = rules.manta_sv.output.vcf,
        delly = rules.delly_sv.output.vcf
    output:
        list_file = PATH + "{sample}/sv/merged/{sample}_vcf_list.txt",
        vcf = PATH + "{sample}/sv/merged/{sample}_merged_SV.vcf"
    conda:
        CONDAENV + "survivor.yaml"
    shell:
        """
        zcat {input.manta} > {PATH}/{wildcards.sample}/sv/merged/manta.vcf
        zcat {input.delly} > {PATH}/{wildcards.sample}/sv/merged/delly.vcf

        printf "%s\\n" \
            {PATH}/{wildcards.sample}/sv/merged/manta.vcf \
            {PATH}/{wildcards.sample}/sv/merged/delly.vcf \
            > {output.list_file}

        SURVIVOR merge {output.list_file} 1000 1 1 1 0 50 {output.vcf}
        """

##########################################################################
# AnnotSV                                                                #
##########################################################################

rule annotsv_annotation:
    input:
        vcf = rules.survivor_merge.output.vcf
    output:
        tsv = PATH + "{sample}/sv/merged/{sample}_merged_SV.annotsv.tsv"
    params:
        outdir = PATH + "{sample}/sv/merged",
        hpo_flag = lambda wc: f"-hpo {HPO_TERMS}" if HPO_TERMS else ""
    conda:
        CONDAENV + "annotsv.yaml"
    shell:
        """
        AnnotSV -SVinputFile {input.vcf} \
            -outputDir {params.outdir} \
            -outputFile {wildcards.sample}_merged_SV.annotsv.tsv \
            -genomeBuild GRCh38 \
            -candidateGenesFile {GENE_LIST} \
            -candidateGenesFiltering 0 \
            {params.hpo_flag}
        """

##################################################################
# VEP                                                             #
##################################################################

rule vep_sv_annotation:
    input:
        vcf = rules.survivor_merge.output.vcf
    output:
        txt = PATH + "{sample}/sv/vep/{sample}_SV_VEP.txt"
    conda:
        CONDAENV + "vep.yaml"
    shell:
        """
        vep --input_file {input.vcf} --format vcf \
            --output_file {output.txt} \
            --cache --offline --dir_cache {VEP_CACHE_DIR} --assembly {VEP_ASSEMBLY} \
            --canonical --overlaps --pick --symbol --biotype \
            --max_sv_size 250000000 --batch_size 100 --fork {THREADS}
        """

######################
# MEI (MELT)         #
######################

rule melt_mei:
    input:
        bam = lambda wc: BAMS[wc.sample],
        ref = REF
    output:
        vcf = PATH + "{sample}/mei/melt/{sample}.MEI.merged.vcf"
    params:
        outdir = PATH + "{sample}/mei/melt",
        transposons = " ".join(MELT_TRANSPOSONS)
    conda:
        CONDAENV + "melt.yaml"
    shell:
        """
        java -jar $MELT_HOME/MELT.jar Single \
            -bamfile {input.bam} -h {input.ref} \
            -n {MELT_DIR}/add_bed_files/Hg38/Hg38.genes.bed \
            -t {params.transposons} \
            -w {params.outdir}
        bcftools concat -a {params.outdir}/*.final_comp.vcf -O v -o {output.vcf}
        """

##############################
# REPEAT EXPANSION (EH)      #
##############################

rule expansionhunter_str:
    input:
        bam = lambda wc: BAMS[wc.sample],
        ref = REF,
        catalog = EH_CATALOG
    output:
        vcf = PATH + "{sample}/str/expansionhunter/{sample}_EH.vcf"
    params:
        prefix = PATH + "{sample}/str/expansionhunter/{sample}_EH"
    conda:
        CONDAENV + "expansionhunter.yaml"
    shell:
        """
        ExpansionHunter --reads {input.bam} --reference {input.ref} \
            --variant-catalog {input.catalog} --output-prefix {params.prefix} \
            --threads {THREADS}
        """

##################################
# SMALL VARIANTS (DeepVariant)   #
##################################

rule deepvariant_snp:
    input:
        bam = lambda wc: BAMS[wc.sample],
        ref = REF
    output:
        vcf = PATH + "{sample}/snp_deepvariant/{sample}.vcf.gz"
    params:
        outdir = PATH + "{sample}/snp_deepvariant"
    conda:
        CONDAENV + "deepvariant.yaml"
    shell:
        """
        run_deepvariant --model_type=WGS \
            --ref={input.ref} --reads={input.bam} \
            --output_vcf={output.vcf} \
            --num_shards={THREADS} \
            --intermediate_results_dir={params.outdir}/intermediate \
            --regions={BED}
        """

######################
# PHASING (WhatsHap)  #
######################

rule whatshap_phasing:
    input:
        vcf = rules.deepvariant_snp.output.vcf,
        bam = lambda wc: BAMS[wc.sample],
        ref = REF
    output:
        phased = PATH + "{sample}/phasing/{sample}.phased.vcf.gz",
        haplotag = PATH + "{sample}/phasing/{sample}.phased.bam"
    conda:
        CONDAENV + "whatshap.yaml"
    shell:
        """
        whatshap phase --reference {input.ref} -o {output.phased} \
            {input.vcf} {input.bam} --ignore-read-groups

        tabix -p vcf {output.phased}

        whatshap haplotag -o {output.haplotag} --reference {input.ref} \
            {output.phased} {input.bam} --ignore-read-groups

        samtools index {output.haplotag}
        """
